# Generated by Django 6.0.1 on 2026-02-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rawmaterial_rawmaterialvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('material_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterialvariant')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.orderitem')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductMaterialRequirement',
        ),
    ]
