# Generated by Django 6.0.1 on 2026-02-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dailyledger_workestimate_workresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail')], default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='low_stock_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
