# Generated by Django 6.0.1 on 2026-02-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_customer_type_rawmaterial_low_stock_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_cost',
            new_name='retail_price',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawmaterialvariant',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
